### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by mat1jaczyyy** [micdah/RtMidi.Core#12]
The description of this repo implies the library is for .NET Core projects, while the README states it is for .NET Standard. In my netcoreapp2.1 project, I cannot seem to access any of my MIDI hardware.

TestApp.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>win10-x64;osx.10.11-x64</RuntimeIdentifiers>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RtMidi.Core" Version="1.0.46" />
  </ItemGroup>
  
</Project>
```

Program.cs
```
using System;
using System.Collections.Generic;
using System.Linq;

using RtMidi.Core;
using RtMidi.Core.Devices;
using RtMidi.Core.Messages;

namespace TestApp {
    class Program {
        static IMidiOutputDevice oDevice;
        static IMidiInputDevice iDevice;

        static void Main(string[] args) {
            Console.WriteLine($"APIs Available: {MidiDeviceManager.Default.GetAvailableMidiApis().Count().ToString()}");
            foreach (var api in MidiDeviceManager.Default.GetAvailableMidiApis())
                Console.WriteLine($"API: {api}");

            Console.WriteLine($"Outputs Available: {MidiDeviceManager.Default.OutputDevices.Count().ToString()}");
            foreach (var oDeviceInfo in MidiDeviceManager.Default.OutputDevices) {
                Console.WriteLine($"Output Device: {oDeviceInfo.Name}");
                oDevice = oDeviceInfo.CreateDevice();

                oDevice.Open();
                oDevice.Send(new ControlChangeMessage(0, 104, 5));
                oDevice.Dispose();
            }

            Console.WriteLine($"Inputs Available: {MidiDeviceManager.Default.InputDevices.Count().ToString()}");
            foreach (var iDeviceInfo in MidiDeviceManager.Default.InputDevices) {
                try {
                    Console.WriteLine($"Output Device: {iDeviceInfo.Name}");
                    iDevice = iDeviceInfo.CreateDevice();

                    iDevice.ControlChange += MIDIIn;
                    iDevice.Open();

                    Console.WriteLine("Listening...");
                    Console.ReadKey();

                } finally {
                    iDevice.ControlChange -= MIDIIn;
                    iDevice.Dispose();
                }
            }
        }

        static void MIDIIn(IMidiInputDevice sender, in ControlChangeMessage msg) {
            Console.WriteLine(msg.Control.ToString());
        }
    }
}
```

Output:
```
APIs Available: 0
Outputs Available: 0
Inputs Available: 0
```

**Comment by micdah** [comment]
Hi @mat1jaczyyy,

Yeah sorry for the confusion about target framework - I have chosen .Net Standard for the widest possible support including .Net Core runtime, which was my actual goal to support a wider range of OS'es.

I notice that it shows 0 available API's, which indicates the underlying _rtmidi_ library didn't find any supported midi API.

What is the runtime environment? Which OS, what .Net Runtime (.Net Core, .Net Framework etc.), and what architecture (x86/x64)?

**Comment by micdah** [comment]
@mat1jaczyyy I have updated the repo description to reflect that I am targeting the wider .Net Standard, rather than only the .Net Core runtime.

Thanks for pointing out the confusion between the description and the readme.

**Comment by micdah** [comment]
Hi @mat1jaczyyy,

Just tried your code, and I think I have found the issue. For some reason it seems `dotnet run` _current working directory_ behaviour have changed, normally it ought to set it to the output folder, i.e. `bin/Debug/netcoreapp2.1/` but when I inspect `Directory.GetCurrentDirectory()` it just points to whereever `dotnet run` is being executed from.

This is not the same behaviour when using Visual Studio or Jetbrains Rider, not for regular .Net Framework.

But it causes issues for `[DllImport]` which expects to be able to find the relevant _rtmidi_ libraries, which it cannot unless they are in the _current working directory_.

It is easy to fix, though:
```
$ dotnet build
$ cd bin/Debug/netcoreapp2.1/
$ dotnet TestApp.dll
```

**Comment by mat1jaczyyy** [comment]
Sorry for not specifying my platform. I can reproduce this on both Windows 10 and macOS Sierra (both x64). Your fix works though, which is really nice! Good job for finding that.

To eliminate the need for building the app every time, I have moved rtmidi.dll and rtmidi32.dll inside my project folder, where `dotnet run` can load them from the current working directory. This works just fine:

```
$ dotnet run
APIs Available: 1
API: RT_MIDI_API_MACOSX_CORE
Outputs Available: 2
Output Device: Launchpad Open Standalone Port
Output Device: Launchpad Open MIDI Port
Inputs Available: 2
Output Device: Launchpad Open Standalone Port
Listening...
29
29
39
39
19
19
Output Device: Launchpad Open MIDI Port
Listening...
59
49
59
39
49
39
```

Thanks for the quick fix! 👍
