### ISSUE TITLE
RtMidi not reporting SysEx input

### ISSUE THREAD

**Issue by mat1jaczyyy** [micdah/RtMidi.Core#16]
Having a bit of trouble with the SysEx input (which, ironically, I wrote).

Tests I wrote do work and confirm that the library is able to receive and parse them properly. However, I'm trying to listen to a SysEx message event in my application, but it doesn't seem to trigger at all.

I've done debugging to confirm the issue isn't my implementation. SysExMessage.TryDecode is never being called. I've tried tracing the calls back to the best of my knowledge, and it looks like MidiInputDevice.Decode is never called either. I've set a breakpoint at the method's entry point, and it does pause execution if I send a note on/off, but not a SysEx message from my MIDI controller. MidiInputDevice.RtMidiInputDevice_Message exhibits the same behaviour.

Now entering very unfamiliar territory, it seems RtMidiInputDevice.HandleRtMidiCallback is not called either when a SysEx message is triggered. From what I can tell, this method transfers all of the data from RtMidi into the C# library. It is, again, called when I send a note on/off, and stepping into it the message variable does get updated with that information.

To me, this suggests this is an issue with RtMidi not reporting the SysEx received from the MIDI device. I don't know if it's simply not configured to receive this kind of message when it is initialized, or if it's an issue in itself (you mentioned in the README we're using a custom build of RtMidi).

SysEx output works perfectly fine, and I've also confirmed using [MIDI Monitor](https://www.snoize.com/MIDIMonitor/) that the SysEx messages are actually being transmitted both ways: 
![image](https://user-images.githubusercontent.com/13300194/44877095-2d08d380-aca3-11e8-89c3-afbfa3915e3f.png)

So far this has been reproduced on macOS, pending testing on Windows.

**Comment by mat1jaczyyy** [comment]
After testing and debugging, the exact same behavior occurs on Windows (64-bit).

**Comment by mat1jaczyyy** [comment]
I've confirmed this change allows the library to receive SysEx. Making a pull request.

**Comment by micdah** [comment]
@mat1jaczyyy You are awesome! 

I'll have a look at your PR asap, but probably a bit later today. Excellent work!
