### ISSUE TITLE
System Common Messages

### ISSUE THREAD

**Issue by garno-fc** [micdah/RtMidi.Core#23]
Hello! 
We have developed a midi show control / midi timecode about 10 years ago, and I'm trying to get it into the new .net era 😄 

We have used the Sanford.Multimedia.Midi for a long time, as it gives us access to BOTH System Exclusive (SysEx) and System Common messages. Our problem is that it is not .net Standard friendly.

I was really hoping to use this library to accomplish this task of moving our midi library onto .net standard, however I have noticed no support for System Common messages? (Listed here https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message)

Is this something that is implemented here and I'm missing it, or is it something that still needs to be implemented? Thanks!

Greg

**Comment by mat1jaczyyy** [comment]
https://github.com/micdah/RtMidi.Core/blob/bb8caf358e26c718aebc10ebe9d63075ebf5784a/RtMidi.Core/Devices/MidiInputDevice.cs#L100-L112

can be implemented in here easily, i guess returning an enum saying which status message it is is fine enough for you?

**Comment by garno-fc** [comment]
That would be great! 

Additionally, we would also need the ability to send system common messages of a certain type.

Thanks!
Greg

**Comment by mat1jaczyyy** [comment]
Sure, I might get to this in a few days if I catch time, but no clue if micdah will accept it and make a package update tho

**Comment by micdah** [comment]
@mat1jaczyyy @garno-fc I have pushed changes to the repo and implement the System Common messages that were missing, now I'm just trying to get AppVeyor to build it again - something has changes since last, so it's being difficult.

Have to stop for today, but will give it another look later to get it to build again.

**Comment by mat1jaczyyy** [comment]
that was fast lol, i thought you were inactive considering you ignored my other issues

**Comment by micdah** [comment]
@mat1jaczyyy Yeah I have been a bit inactive on this project, but seeing the interest for it, I thought I would throw in some time to make some requested updates 😄 Sorry for ignoring your other issues, will have a look at them as well

**Comment by micdah** [comment]
@garno-fc New nuget package has been published, will be available shortly https://www.nuget.org/packages/RtMidi.Core/1.0.51
