### ISSUE TITLE
How to send Midi Note On/Off signals to PC.

### ISSUE THREAD

**Issue by ca3games** [micdah/RtMidi.Core#27]
Hi, cant find info on how to send notes on/off messages to other applications.

**Comment by micdah** [comment]
Hi, sorry for my extremely late answer, I assume you have gone onto other things - but just for posterior this is how you could go about sending a MIDI message to a output device:

```c#
            var outputDevice = MidiDeviceManager.Default.OutputDevices.First().CreateDevice();
            outputDevice.Send(new NoteOnMessage(Channel.Channel1, Key.Key0, 0));
```

I'm simply taking the first available MIDI output device (for demonstration purpose) and sending a "Note On" message. 

There are C# typed messages for the different MIDI message types, so you don't have to know the byte codes and structure of each 😄
